# .pre-commit-config.yaml
repos:
  # Standard general hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files

  # Backend Python Formatting & Linting (Ruff)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      # Run the formatter first
      - id: ruff-format
        args: ["backend/app"]
        types_or: [python]
      # Run the linter with auto-fix enabled
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, "backend/app"]
        types_or: [python]

  # Frontend Formatting (Prettier)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/
        args: [--write]

  # ESLint - Run via npm script
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd frontend && npm run lint -- --fix'
        language: system
        types: [file]
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
        pass_filenames: false
